# Generated by Django 3.1.5 on 2021-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210117_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
